{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopverse-ingress
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}

  rules:
  - http:
      paths:

      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.frontend.serviceName }}
            port:
              number: {{ .Values.frontend.servicePort }}

      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.serviceName }}
            port:
              number: {{ .Values.backend.servicePort }}

      - path: /health
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.backend.serviceName }}
            port:
              number: {{ .Values.backend.servicePort }}

{{- end }}
